services:
  postgres:
    image: postgis/postgis:latest
    container_name: postgres_db_1
    
    environment:
      POSTGRES_USER: siam         # Define your database username
      POSTGRES_PASSWORD: siam@123 # Define your password
      POSTGRES_DB: inventory-management-db     # Define your database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U siam"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: inventoryManagement
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy  
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=siam
      - POSTGRES_PASSWORD=siam@123
      - POSTGRES_DB=inventory-management-db

volumes:
  postgres_data:



