# Generated by Django 5.1.3 on 2024-11-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='images',
        ),
    ]
