# Generated by Django 5.1.3 on 2024-11-29 20:21

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_accommodation_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationimage',
            name='image',
            field=models.ImageField(upload_to=properties.models.upload_accommodation_image),
        ),
    ]
