# Generated by Django 5.1.3 on 2024-11-29 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_accommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizeAccommodation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=10)),
                ('localized_name', models.CharField(max_length=150)),
                ('localized_description', models.TextField(blank=True, null=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized', to='properties.accommodation')),
            ],
            options={
                'verbose_name': 'Localized Accommodation',
                'verbose_name_plural': 'Localized Accommodations',
                'unique_together': {('accommodation', 'language_code')},
            },
        ),
    ]
